"""init

Revision ID: 19637f07036c
Revises:
Create Date: 2026-04-02 09:34:51.868890

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19637f07036c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("parser_name", sa.String(length=64), nullable=False),
        sa.Column("read_cmd_hex", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "parsed_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("port", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.String(length=4), nullable=False),
        sa.Column("raw_hex", sa.Text(), nullable=False),
        sa.Column("parsed_json", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parsed_records_device_id"), "parsed_records", ["device_id"], unique=False)
    op.create_index(op.f("ix_parsed_records_timestamp"), "parsed_records", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parsed_records_timestamp"), table_name="parsed_records")
    op.drop_index(op.f("ix_parsed_records_device_id"), table_name="parsed_records")
    op.drop_table("parsed_records")
    op.drop_table("devices")
    # ### end Alembic commands ###
