"""add step port config to devices

Revision ID: 2e50a5cedcf0
Revises: e7f8a9b0c1d2
Create Date: 2026-04-22 11:59:36.613381

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e50a5cedcf0"
down_revision: str | Sequence[str] | None = "e7f8a9b0c1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("step_port", sa.String(length=32), nullable=True))
    op.add_column("devices", sa.Column("step_baudrate", sa.Integer(), nullable=True))
    op.add_column("devices", sa.Column("step_bytesize", sa.Integer(), nullable=True))
    op.add_column("devices", sa.Column("step_parity", sa.String(length=4), nullable=True))
    op.add_column("devices", sa.Column("step_stopbits", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "step_stopbits")
    op.drop_column("devices", "step_parity")
    op.drop_column("devices", "step_bytesize")
    op.drop_column("devices", "step_baudrate")
    op.drop_column("devices", "step_port")
    # ### end Alembic commands ###
